# device permissions + driver loading on hotplug
$MODALIAS=.*  root:root 0660 @modprobe -q "$MODALIAS"
null          root:root 0666
zero          root:root 0666
full          root:root 0666
random        root:root 0666
urandom       root:root 0666
tty           root:tty  0666
ptmx          root:tty  0666
dri/.*        root:video 0660
snd/.*        root:audio 0660
input/.*      root:input 0660
