# Add networks with:  wpa_passphrase "SSID" >> /etc/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=DIR=/run/wpa_supplicant GROUP=root
update_config=1
# privacy: random MAC per network and while scanning
mac_addr=1
preassoc_mac_addr=1
gas_rand_mac_addr=1
